apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-green 
  namespace: expense
  # lables of deployment resource
  labels:
    app: backend
    tier: backend
    purpose: expense
    version: green
spec:
  replicas: 1
  selector:   #slectors are lables
    matchLabels:
       app: backend
       tier: backend
       purpose: expense
       version: green
  template:
    metadata:
      labels:
         app: backend
         tier: backend
         purpose: expense
         version: green
    spec:
      containers:
      - name: nginx
        image: prc1196/backend:3.0.0
        envFrom:
        - configMapRef:
            name: backend