kind: Service
apiVersion: v1
metadata:
  name: backend
  namespace: expense
spec:
  selector:   #lables are used as selectors
    app: backend
    tier: backend
    purpose: expense
    version: blue
  ports:
  - protocol: TCP
    port: 8080  #service port
    targetPort: 8080

   